### ISSUE TITLE
Multiple CSS Selectors

### ISSUE THREAD

**Issue by cyouh95** [justamanda/prj-rev-bwfs-dasmoto#2]
Instead of having to write `font-weight:bold;` 3 times for each of the different elements, you could specify shared properties for multiple elements at once by including all the selectors separated by commas:

```css
h1, h2, .bold {
  font-weight:bold;
}
```

https://github.com/justamanda/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/resources/index.css#L6
https://github.com/justamanda/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/resources/index.css#L14
https://github.com/justamanda/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/resources/index.css#L17

**Comment by justamanda** [comment]
That's a good point. I didn't realize those were all bold until I got to that point, so if I had looked it over a little better in the first place that is a good thought :)
